apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: cloudinit-service
  name: cloudinit-service
  namespace: default
spec:
  rules:
    - host: cloudinit-service.virtualthoughts.co.uk
      http:
        paths:
          - backend:
              service:
                name: cloudinit-service
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
status:
  loadBalancer:
    ingress:
      - ip: 172.16.10.121
---
kind: Service
apiVersion: v1
metadata:
  name: cloudinit-service
spec:
  selector:
    app: cloudinit-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudinit-service
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudinit-service
  template:
    metadata:
      labels:
        app: cloudinit-service
    spec:
      containers:
        - name: cloudinit-service
          image: nginx:1.20.1
          ports:
            - containerPort: 80
          volumeMounts:
            - name: cloudinit
              mountPath: /usr/share/nginx/html/
      volumes:
        - name: cloudinit
          configMap:
            name: dir