name: Build

on: [pull_request, workflow_dispatch]

jobs:
  Build_ubuntu_2004_subiquity:
    runs-on: self-hosted
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: fix
          target: ./vSphere/ubuntu_2004_subiquity/ubuntu-2004.json

      # Grab config file
      - name: Generate variables.json
        run : echo ${{ secrets.PACKER_CONFIG_BASE64 }} | base64 -d > ./vSphere/ubuntu_2004_subiquity/variables.json

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: ./vSphere/ubuntu_2004_subiquity/ubuntu-2004.json

      # Upload Configmap
      - name: Upload Configmap & Publish Cloud-Init Data
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: create configmap dir --from-file=./vSphere/ubuntu_2004_subiquity/http && kubectl apply -f .github/cloud-init.yaml

      # Replace HTTP reference
      - name: Replace HTTP reference
        run : sed -i 's/{{ .HTTPIP }}:{{ .HTTPPort }}/cloudinit-service.virtualthoughts.co.uk/g' ./vSphere/ubuntu_2004_subiquity/ubuntu-2004.json

      # Build Template
      - name: Build Template - Ubuntu 2004
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort --var-file=./vSphere/ubuntu_2004_subiquity/variables.json -force"
          target: ./vSphere/ubuntu_2004_subiquity/ubuntu-2004.json

      # cleanup
      - name: Delete Configmap & Remove Cloud-Init Data

        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: delete cm dir && kubectl delete -f .github/cloud-init.yaml
