name: Build Packer Templates

on: [pull_request, workflow_dispatch]

jobs:
  Build_ubuntu_2004_subiquity:
    runs-on: self-hosted
    name: Build ubuntu_2004_subiquity

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          working_directory: ./vSphere/ubuntu_2004_subiquity/
          command: fix
          target: ubuntu-2004.json


      # Grab config file
      - name: Generate variables.json
        run : echo ${{ secrets.PACKER_CONFIG_BASE64 }} | base64 -d > ./vSphere/ubuntu_2004_subiquity/variables.json

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          working_directory: ./vSphere/ubuntu_2004_subiquity/
          command: validate
          arguments: -syntax-only
          target: ubuntu-2004.json

      # Upload Configmap
      - name: Upload Configmap & Publish Cloud-Init Data
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: create configmap dir --from-file=./vSphere/ubuntu_2004_subiquity/http && kubectl apply -f .github/cloud-init.yaml

      # Replace HTTP reference
      - name: Replace HTTP reference
        run : sed -i 's/{{ .HTTPIP }}:{{ .HTTPPort }}/cloudinit-service.virtualthoughts.co.uk/g' ./vSphere/ubuntu_2004_subiquity/ubuntu-2004.json

      # Build Template
      - name: Build Template - Ubuntu 2004
        uses: hashicorp/packer-github-actions@master
        with:
          working_directory: ./vSphere/ubuntu_2004_subiquity/
          command: build
          arguments: "-color=false -on-error=abort --var-file=variables.json -force"
          target: ubuntu-2004.json

      # cleanup
      - name: Delete Configmap & Remove Cloud-Init Data

        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: delete cm dir && kubectl delete -f .github/cloud-init.yaml

  Build_centos_7:
    runs-on: self-hosted
    name: Build centos_7

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          working_directory: ./vSphere/centos_7/
          command: fix
          target: centos7.json

      # Grab config file
      - name: Generate variables.json
        run : echo ${{ secrets.PACKER_CONFIG_BASE64 }} | base64 -d > ./vSphere/centos_7/variables.json

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          working_directory: ./vSphere/centos_7/
          command: validate
          arguments: -syntax-only
          target: centos7.json

      # Upload Configmap
      - name: Upload Configmap & Publish Cloud-Init Data
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: create configmap dir --from-file=./vSphere/centos_7/http && kubectl apply -f .github/cloud-init.yaml

      # Replace HTTP reference
      - name: Replace HTTP reference
        run : sed -i 's/{{ .HTTPIP }}:{{ .HTTPPort }}/cloudinit-service.virtualthoughts.co.uk/g' ./vSphere/centos_7/centos7.json

      # Build Template
      - name: Build Template - Centos 7
        uses: hashicorp/packer-github-actions@master
        with:
          working_directory: ./vSphere/centos_7/
          command: build
          arguments: "-color=false -on-error=abort --var-file=variables.json -force"
          target: centos7.json

      # cleanup
      - name: Delete Configmap & Remove Cloud-Init Data

        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: delete cm dir && kubectl delete -f .github/cloud-init.yaml

  Build_opensuse_leap_15:
    runs-on: self-hosted
    name: opensuse_leap_15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          working_directory: ./vSphere/opensuse_leap_15.2/
          command: fix
          target: opensuse-leap-15.2-x86_64.json


      # Grab config file
      - name: Generate variables.json
        run : echo ${{ secrets.PACKER_CONFIG_BASE64 }} | base64 -d > ./vSphere/opensuse_leap_15.2/variables.json

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          working_directory: ./vSphere/opensuse_leap_15.2/
          command: validate
          arguments: -syntax-only
          target: opensuse-leap-15.2-x86_64.json

      # Build Template
      - name: Build Template - Opensuse Leap 15.2
        uses: hashicorp/packer-github-actions@master
        with:
          working_directory: ./vSphere/opensuse_leap_15.2/
          command: build
          arguments: "-color=false -on-error=abort --var-file=variables.json -force"
          target: opensuse-leap-15.2-x86_64.json

  Build_sles_15_SP2:
    runs-on: self-hosted
    name: sles_15_SP2

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          working_directory: ./vSphere/sles_15_sp2/
          command: fix
          target: sles-15sp2.json

      # Grab config file
      - name: Generate variables.json
        run : echo ${{ secrets.PACKER_CONFIG_BASE64 }} | base64 -d > ./vSphere/sles_15_sp2/variables.json

      # Replace ISO reference
      - name: Replace ISO reference
        run : sed -i 's,"./SLE-15-SP2-Online-x86_64-GM-Media1.iso","https://minio.virtualthoughts.co.uk:9000/iso/SLE-15-SP2-Online-x86_64-GM-Media1.iso",g' ./vSphere/sles_15_sp2/sles-15sp2.json

      # Replace Reg Code reference
      - name: Replace Reg Code reference
        run : sed -i "s/YOUR_REG_CODE_HERE/${{ secrets.SCC_CODE }}/g" ./vSphere/sles_15_sp2/autoinst.xml

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          working_directory: ./vSphere/sles_15_sp2/
          command: validate
          arguments: -syntax-only
          target: sles-15sp2.json

      # Build Template
      - name: Build Template - Opensuse Leap 15.2
        uses: hashicorp/packer-github-actions@master
        with:
          working_directory: ./vSphere/sles_15_sp2/
          command: build
          arguments: "-color=false -on-error=abort --var-file=variables.json -force"
          target: sles-15sp2.json

  Build_ubuntu_1804:
    runs-on: self-hosted
    name: ubuntu_1804

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          working_directory: ./vSphere/ubuntu_1804/
          command: fix
          target: ubuntu-18.json

      # Grab config file
      - name: Generate variables.json
        run : echo ${{ secrets.PACKER_CONFIG_BASE64 }} | base64 -d > ./vSphere/ubuntu_1804/variables.json

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          working_directory: ./vSphere/ubuntu_1804/
          command: validate
          arguments: -syntax-only
          target: ubuntu-18.json

      # Build Template
      - name: Build Template - Ubuntu 18.04
        uses: hashicorp/packer-github-actions@master
        with:
          working_directory: ./vSphere/ubuntu_1804/
          command: build
          arguments: "-color=false -on-error=abort --var-file=variables.json -force"
          target: ubuntu-18.json

  Build_ubuntu_1804_no_dhcp:
    runs-on: self-hosted
    name: ubuntu_1804_no_dhcp

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          working_directory: ./vSphere/ubuntu_1804_no_dhcp/
          command: fix
          target: ubuntu-18.json

      # Grab config file
      - name: Generate variables.json
        run : echo ${{ secrets.PACKER_CONFIG_BASE64 }} | base64 -d > ./vSphere/ubuntu_1804_no_dhcp/variables.json

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          working_directory: ./vSphere/ubuntu_1804_no_dhcp/
          command: validate
          arguments: -syntax-only
          target: ubuntu-18.json

      # Build Template
      - name: Build Template - Ubuntu 18.04
        uses: hashicorp/packer-github-actions@master
        with:
          working_directory: ./vSphere/ubuntu_1804_no_dhcp/
          command: build
          arguments: "-color=false -on-error=abort --var-file=variables.json -force"
          target: ubuntu-18.json