name: tesst-opensuse-leap

on: [pull_request, workflow_dispatch]

jobs:
  Build_opensuse_leap_15:
    runs-on: self-hosted
    name: opensuse_leap_15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          working_directory: ./vSphere/opensuse_leap_15.2/
          command: fix
          target: opensuse-leap-15.2-x86_64.json


      # Grab config file
      - name: Generate variables.json
        run : echo ${{ secrets.PACKER_CONFIG_BASE64 }} | base64 -d > ./vSphere/opensuse_leap_15.2/variables.json

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          working_directory: ./vSphere/opensuse_leap_15.2/
          command: validate
          arguments: -syntax-only
          target: opensuse-leap-15.2-x86_64.json

      # Build Template
      - name: Build Template - Opensuse Leap 15.2
        uses: hashicorp/packer-github-actions@master
        with:
          working_directory: ./vSphere/opensuse_leap_15.2/
          command: build
          arguments: "-color=false -on-error=abort --var-file=variables.json -force"
          target: opensuse-leap-15.2-x86_64.json

      # cleanup
      - name: Delete Configmap & Remove Cloud-Init Data

        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: delete cm dir && kubectl delete -f .github/cloud-init.yaml
